# Hacker Rank Code Challenges: Numpy

## Introduction: 

Numpy is a popular statistical package in Python that is often used by data scientists for manipulating and operating upon data sets. Hacker Rank provides a series of challenges using numpy that we will attempt to solve here.

In [3]:
# Import library
import numpy as np

### Challenges- 

#### 1) "Eye and Identity":

The task is to print an array of size X with its main diagonal elements as 1's and 0's everywhere else.

*Note- in Hacker Rank, there is a bug; so the output must be fixed to match the expected values

#### Code- 

In [4]:
# Interpret the inputs
a, b = map(int, input().split())

# Create the array
eye = numpy.eye(a, b, k = 0)

# Fix values to match bug
out = str(eye).replace('0', ' 0').replace('1', ' 1')

print(out)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 2) "Array Mathematics":

Given arrays of various dimensions, our task here is to perform the following operations:

* Add
* Subtract
* Multiply
* Divide
* Mod (%)
* Power

*Note- we are asked to use // for division in Python 3

#### Code- 

In [ ]:
# Read user input
n, m = map(int, input().split())
a, b = (np.array([input().split() for _ in range(n)], dtype=int) for _ in range(2))

# Results
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')